version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/helio/Documentos/esoteric-bot/project:/home/helio/Documentos/esoteric-bot/project
    restart: unless-stopped
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
    networks:
      - jenkins_network
    user: root  # Execute Jenkins como root para evitar problemas de permissões

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
