version: '3.8'

services:
  postgres:
    image: postgres:9.6
    container_name: pg-tasks
    environment:
      POSTGRES_DB: tasks
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
