import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Header from "./components/header/header";
import { Providers } from "./providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers> {/* Agora dentro de <body> */}
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
